# Set the base image to Ubuntu
FROM ubuntu

# File Author / Email
MAINTAINER Eric Koh <EricKoh.dev@gmail.com>

# Replace repo
COPY sources.list /etc/apt/sources.list

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get -y install python build-essential nodejs

# Install nodemon
RUN npm install -g nodemon --registry=https://registry.npm.taobao.org

# Provides cached layer for node_modules
COPY package.json /tmp/
RUN cd /tmp && npm install --registry=https://registry.npm.taobao.org
#ENV NODE_PATH=/tmp/node_modules

# Define working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN cp -a /tmp/node_modules /usr/src/app/

# Expose port
EXPOSE  8080

# Run app using nodemon
CMD npm run dev
